# 配置数据源
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3310/hr_db
    username: root
    password: 16436131
    driverClassName: com.mysql.jdbc.Driver
# 配置乱码解决方案
  http:
    encoding: 
      force: true
      charset: utf-8
      enabled: true
server: 
  tomcat: 
    uriEncoding: utf-8 
    
# 配置mybatis的信息
mybatis: 
  mapperLocations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.dsc.hr.base.pojo

    
    